from faker import Faker
import os
import random
import requests

from app.core.db import get_db
from app.models.user import Users
from app.models.url import URLModel

# ======================================================================
# Configuration
# ======================================================================

fake = Faker()

DOMAIN = os.getenv("API_BASE_URL", "http://localhost:8000")

REGISTER_USER_API = f"{DOMAIN}/v1/auth/register_user"
LOGIN_USER_API = f"{DOMAIN}/v1/auth/login-json"
CREATE_URL_API = f"{DOMAIN}/v1/urls/"  # Change if different

PASSWORD = "secretpassword"
TOTAL_USERS = 100
TOTAL_URLS = 1000

# ======================================================================
# Helpers
# ======================================================================


def generate_emails():
    emails = set()

    while len(emails) < TOTAL_USERS:
        emails.add(
            f"{fake.first_name().lower()}.{fake.last_name().lower()}@fastapi.com"
        )

    return list(emails)


def create_users():
    print("=" * 70)
    print("Creating Users")
    print("=" * 70)

    for email in generate_emails():
        payload = {
            "email": email,
            "password": PASSWORD,
        }

        response = requests.post(
            REGISTER_USER_API,
            json=payload,
            timeout=10,
        )

        if response.status_code == 200:
            print(f"Created: {email}")
        else:
            print(f"Skipped: {email}")
            print(response.text)


def get_users():
    db = next(get_db())
    users = db.query(Users).all()
    return [user.email for user in users]



all_urls = [
    "https://youtube.com",
    "https://facebook.com",
    "https://instagram.com",
    "https://wikipedia.org",
    "https://reddit.com",
    "https://tiktok.com",
    "https://pinterest.com",
    "https://quora.com",
    "https://amazon.com",
    "https://google.com",
    "https://fandom.com",
    "https://apple.com",
    "https://x.com",
    "https://yahoo.com",
    "https://yelp.com",
    "https://linkedin.com",
    "https://imdb.com",
    "https://ebay.com",
    "https://mapquest.com",
    "https://scribd.com",
    "https://tripadvisor.com",
    "https://britannica.com",
    "https://etsy.com",
    "https://wordpress.com",
    "https://cambridge.org",
    "https://shutterstock.com",
    "https://walmart.com",
    "https://medium.com",
    "https://spotify.com",
    "https://merriam-webster.com",
    "https://nih.gov",
    "https://dailymotion.com",
    "https://collinsdictionary.com",
    "https://wiktionary.org",
    "https://reverso.net",
    "https://wordreference.com",
    "https://wheree.com",
    "https://healthline.com",
    "https://dictionary.com",
    "https://nytimes.com",
    "https://indeed.com",
    "https://study.com",
    "https://adobe.com",
    "https://yahoo.co.jp",
    "https://istockphoto.com",
    "https://clevelandclinic.org",
    "https://bbc.com",
    "https://vocabulary.com",
    "https://webmd.com",
    "https://bbc.co.uk",
    "https://gettyimages.com",
    "https://booking.com",
    "https://sciencedirect.com",
    "https://bab.la",
    "https://rottentomatoes.com",
    "https://wikihow.com",
    "https://amazon.co.uk",
    "https://stackexchange.com",
    "https://thefreedictionary.com",
    "https://mayoclinic.org",
    "https://weebly.com",
    "https://target.com",
    "https://threads.com",
    "https://justanswer.com",
    "https://yourdictionary.com",
    "https://indiatimes.com",
    "https://researchgate.net",
    "https://trip.com",
    "https://netflix.com",
    "https://waze.com",
    "https://microsoft.com",
    "https://namu.wiki",
    "https://theguardian.com",
    "https://genius.com",
    "https://medicalnewstoday.com",
    "https://msn.com",
    "https://amazon.de",
    "https://primevideo.com",
    "https://substack.com",
    "https://espn.com",
    "https://homedepot.com",
    "https://lemon8-app.com",
    "https://baidu.com",
    "https://forbes.com",
    "https://grokipedia.com",
    "https://wordhippo.com",
    "https://themoviedb.org",
    "https://naver.com",
    "https://ign.com",
    "https://screenrant.com",
    "https://yellowpages.com",
    "https://dreamstime.com",
    "https://glosbe.com",
    "https://harvard.edu",
    "https://ubereats.com",
    "https://usnews.com",
    "https://alamy.com",
    "https://aliexpress.com",
    "https://usatoday.com",
    "https://slideshare.net",
    "https://kiddle.co",
    "https://amazon.in",
    "https://oxfordlearnersdictionaries.com",
    "https://ldoceonline.com",
    "https://thesaurus.com",
    "https://aol.com",
    "https://wikimedia.org",
    "https://wanderlog.com",
    "https://cnn.com",
    "https://byjus.com",
    "https://expedia.com",
    "https://businessinsider.com",
    "https://justwatch.com",
    "https://cbsnews.com",
    "https://tripadvisor.co.uk",
    "https://hotels.com",
    "https://ebay.co.uk",
    "https://soundcloud.com",
    "https://goodreads.com",
    "https://rakuten.co.jp",
    "https://amazon.ca",
    "https://agoda.com",
    "https://www.nhs.uk",
    "https://oed.com",
    "https://medlineplus.gov",
    "https://freepik.com",
    "https://restaurantguru.com",
    "https://geeksforgeeks.org",
    "https://ebsco.com",
    "https://trustpilot.com",
    "https://allrecipes.com",
    "https://alibaba.com",
    "https://people.com",
    "https://softonic.com",
    "https://lingolandedu.com",
    "https://cnet.com",
    "https://brainly.in",
    "https://ameblo.jp",
    "https://langeek.co",
    "https://gamespot.com",
    "https://note.com",
    "https://tvguide.com",
    "https://wikiwand.com",
    "https://vedantu.com",
    "https://answers.com",
    "https://justdial.com",
    "https://github.com",
    "https://wisdomlib.org",
    "https://independent.co.uk",
    "https://lowes.com",
    "https://verywellhealth.com",
    "https://today.com",
    "https://bbb.org",
    "https://sofascore.com",
    "https://hinative.com",
    "https://investopedia.com",
    "https://magnific.com",
    "https://khanacademy.org",
    "https://letterboxd.com",
    "https://pixabay.com",
    "https://tistory.com",
    "https://goodrx.com",
    "https://canva.com",
    "https://vecteezy.com",
    "https://hindustantimes.com",
    "https://encyclopedia.com",
    "https://doordash.com",
    "https://ck12.org",
    "https://etymonline.com",
    "https://amazon.fr",
    "https://uptodown.com",
    "https://sportskeeda.com",
    "https://cookpad.com",
    "https://amazon.co.jp",
    "https://zillow.com",
    "https://tvtropes.org",
    "https://studocu.com",
    "https://globo.com",
    "https://yandex.ru",
    "https://flipkart.com",
    "https://weblio.jp",
    "https://investing.com",
    "https://bestbuy.com",
    "https://testbook.com",
    "https://uol.com.br",
    "https://quizlet.com",
    "https://plex.tv",
    "https://amazon.com.au",
    "https://maptons.com",
    "https://gamerant.com",
    "https://thoughtco.com",
    "https://bbcgoodfood.com",
    "https://famousbirthdays.com",
    "https://accuweather.com",
    "https://pons.com",
    "https://tripadvisor.in",
    "https://letras.com",
    "https://timeout.com",
    "https://mubi.com",
    "https://steampowered.com",
    "https://archive.org",
    "https://ikea.com",
    "https://tripadvisor.ca",
    "https://as.com",
    "https://steamcommunity.com",
    "https://pbs.org",
    "https://mercadolivre.com.br",
    "https://techradar.com",
    "https://foxnews.com",
    "https://libretexts.org",
    "https://nbcnews.com",
    "https://ebay.de",
    "https://ndtv.com",
    "https://ca.gov",
    "https://ziprecruiter.com",
    "https://allocine.fr",
    "https://powerthesaurus.org",
    "https://timeanddate.com",
    "https://definitions.net",
    "https://rae.es",
    "https://nextdoor.com",
    "https://cdc.gov",
    "https://realtor.com",
    "https://howstuffworks.com",
    "https://healthgrades.com",
    "https://lingvanex.com",
    "https://glassdoor.com",
    "https://parade.com",
    "https://vocal.media",
    "https://tumblr.com",
    "https://shabdkosh.com",
    "https://thespruce.com",
    "https://indiamart.com",
    "https://unsplash.com",
    "https://kayak.com",
    "https://prezi.com",
    "https://wikidata.org",
    "https://si.com",
    "https://springer.com",
    "https://collider.com",
    "https://cbr.com",
    "https://yelp.ca",
    "https://foxsports.com",
    "https://pagesjaunes.fr",
    "https://pcmag.com",
    "https://cosmopolitan.com",
    "https://idealo.de",
    "https://365scores.com",
    "https://filmaffinity.com",
    "https://wise.com",
    "https://tripadvisor.de",
    "https://navitime.co.jp",
    "https://reuters.com",
    "https://amazon.es",
    "https://www.gov.uk",
    "https://onelook.com",
    "https://foodnetwork.com",
    "https://kleinanzeigen.de",
    "https://letras.mus.br",
    "https://getyourguide.com",
    "https://urbandictionary.com",
    "https://cnbc.com",
    "https://europa.eu",
    "https://weather.com",
    "https://thekitchn.com",
    "https://food.com",
    "https://larousse.fr",
    "https://southernliving.com",
    "https://macys.com",
    "https://infobae.com",
    "https://ouest-france.fr",
    "https://makemytrip.com",
    "https://opentable.com",
    "https://mercari.com",
    "https://medicinenet.com",
    "https://nordstrom.com",
    "https://hopkinsmedicine.org",
    "https://rome2rio.com",
    "https://bloomberg.com",
    "https://wordwebonline.com",
    "https://drugs.com",
    "https://economictimes.com",
    "https://pexels.com",
    "https://tripadvisor.fr",
    "https://cbssports.com",
    "https://shazam.com",
    "https://seriouseats.com",
    "https://poshmark.com",
    "https://instacart.com",
    "https://goodhousekeeping.com",
    "https://tripadvisor.ie",
    "https://vaia.com",
    "https://shopee.co.id",
    "https://flickr.com",
    "https://news18.com",
    "https://aiscore.com",
    "https://fiveable.me",
    "https://tuasaude.com",
    "https://skysports.com",
    "https://msdmanuals.com",
    "https://askfilo.com",
    "https://en-academic.com",
    "https://mercadolibre.com.mx",
    "https://infobel.com",
    "https://telegraph.co.uk",
    "https://filmweb.pl",
    "https://amazon.it",
    "https://moovitapp.com",
    "https://fandango.com",
    "https://detik.com",
    "https://canada.ca",
    "https://everydayhealth.com",
    "https://amazon.com.br",
    "https://nationalgeographic.com",
    "https://mappy.com",
    "https://apkpure.com",
    "https://prom.ua",
    "https://hollywoodreporter.com",
    "https://omnicalculator.com",
    "https://variety.com",
    "https://olx.ua",
    "https://ranker.com",
    "https://stackoverflow.com",
    "https://cornell.edu",
    "https://rollingstone.com",
    "https://thesun.co.uk",
    "https://buzzfeed.com",
    "https://elle.com",
    "https://company-information.service.gov.uk",
    "https://nypost.com",
    "https://wikivoyage.org",
    "https://musixmatch.com",
    "https://nature.com",
    "https://health.com",
    "https://latimes.com",
    "https://mirror.co.uk",
    "https://healthdirect.gov.au",
    "https://alchetron.com",
    "https://npr.org",
    "https://kumparan.com",
    "https://spanishdict.com",
    "https://medscape.com",
    "https://tasteofhome.com",
    "https://tokopedia.com",
    "https://linguee.com",
    "https://vdict.com",
    "https://accio.com",
    "https://snapchat.com",
    "https://cbc.ca",
    "https://sportingnews.com",
    "https://gettyimages.fr",
    "https://apnews.com",
    "https://azlyrics.com",
    "https://dw.com",
    "https://time.com",
    "https://express.co.uk",
    "https://newsweek.com",
    "https://hm.com",
    "https://birdeye.com",
    "https://website-files.com",
    "https://grubhub.com",
    "https://samsung.com",
    "https://worldatlas.com",
    "https://shopee.com.br",
    "https://tabelog.com",
    "https://edmunds.com",
    "https://kbb.com",
    "https://viator.com",
    "https://alltrails.com",
    "https://thespruceeats.com",
    "https://indianexpress.com",
    "https://mindtrip.ai",
    "https://dailymail.com",
    "https://infoplease.com",
    "https://instructables.com",
    "https://tomsguide.com",
    "https://cars.com",
    "https://flashscore.com",
    "https://wordsmyth.net",
    "https://tripadvisor.co.nz",
    "https://thegamer.com",
    "https://ingles.com",
    "https://barnesandnoble.com",
    "https://tvinsider.com",
    "https://bol.com",
    "https://rozetka.com.ua",
    "https://brainly.com",
    "https://travelocity.com",
    "https://deezer.com",
    "https://linguix.com",
    "https://discogs.com",
    "https://walmart.ca",
    "https://goal.com",
    "https://mnemonicdictionary.com",
    "https://yandex.com",
    "https://almaany.com",
    "https://wayfair.com",
    "https://tradingview.com",
    "https://tripadvisor.it",
    "https://homes.com",
    "https://atly.com",
    "https://tripadvisor.es",
    "https://wsj.com",
    "https://vogue.com",
    "https://mapy.com",
    "https://trulia.com",
    "https://huffpost.com",
    "https://theconversation.com",
    "https://abc.net.au",
    "https://jiosaavn.com",
    "https://history.com",
    "https://line.me",
    "https://klook.com",
    "https://daum.net",
    "https://washingtonpost.com",
    "https://a-z-animals.com",
    "https://gamesradar.com",
    "https://nsw.gov.au",
    "https://quillbot.com",
    "https://ew.com",
    "https://ebay.com.au",
    "https://nasa.gov",
    "https://apartments.com",
    "https://moneycontrol.com",
    "https://last.fm",
    "https://lazada.co.id",
    "https://usda.gov",
    "https://radiotimes.com",
    "https://lefigaro.fr",
    "https://zoominfo.com",
    "https://caranddriver.com",
    "https://foodandwine.com",
    "https://johnlewis.com",
    "https://droracle.ai",
    "https://wiley.com",
    "https://mapcarta.com",
    "https://com.be",
    "https://timesnownews.com",
    "https://mashable.com",
    "https://marca.com",
    "https://elpais.com",
    "https://who.int",
    "https://kompas.com",
    "https://carfax.com",
    "https://gutefrage.net",
    "https://redfin.com",
    "https://gelbeseiten.de",
    "https://lawinsider.com",
    "https://worldometers.info",
    "https://csfd.cz",
    "https://cuemath.com",
    "https://otto.de",
    "https://nps.gov",
    "https://tenor.com",
    "https://yellowpages.ca",
    "https://liputan6.com",
    "https://asos.com",
    "https://nike.com",
    "https://practo.com",
    "https://marthastewart.com",
    "https://dickssportinggoods.com",
    "https://tripadvisor.com.au",
    "https://deviantart.com",
    "https://the-sun.com",
    "https://fotmob.com",
    "https://corriere.it",
    "https://tastingtable.com",
    "https://vimeo.com",
    "https://wikimapia.org",
    "https://bajajfinserv.in",
    "https://tubitv.com",
    "https://biblegateway.com",
    "https://gymglish.com",
    "https://consumerreports.org",
    "https://pngtree.com",
    "https://houzz.com",
    "https://academia.edu",
    "https://psychologytoday.com",
    "https://transfermarkt.com",
    "https://movieweb.com",
    "https://traveloka.com",
    "https://menshealth.com",
    "https://redbubble.com",
    "https://tripadvisor.ch",
    "https://gotquestions.org",
    "https://inchcalculator.com",
    "https://billboard.com",
    "https://thehindu.com",
    "https://si.edu",
    "https://marriott.com",
    "https://youtu.be",
    "https://yell.com",
    "https://download.it",
    "https://abcnews.com",
    "https://masterclass.com",
    "https://thesaurus.altervista.org",
    "https://wired.com",
    "https://alberta.ca",
    "https://nerdwallet.com",
    "https://mlb.com",
    "https://stanford.edu",
    "https://lenovo.com",
    "https://wordnik.com",
    "https://ny.gov",
    "https://livescience.com",
    "https://vk.com",
    "https://arcgis.com",
    "https://yandex.com.tr",
    "https://postmates.com",
    "https://texas.gov",
    "https://depositphotos.com",
    "https://brainly.lat",
    "https://thesaurus.plus",
    "https://unacademy.com",
    "https://chip.de",
    "https://livhospital.com",
    "https://cylex-uk.co.uk",
    "https://dhgate.com",
    "https://lyricstranslate.com",
    "https://ultimate-guitar.com",
    "https://longdo.com",
    "https://docomo.ne.jp",
    "https://lumenlearning.com",
    "https://tribunnews.com",
    "https://magazineluiza.com.br",
    "https://kidshealth.org",
    "https://disneyplus.com",
    "https://t-online.de",
    "https://1mg.com",
    "https://ebay.ca",
    "https://costco.com",
    "https://besoccer.com",
    "https://recipetineats.com",
    "https://aljazeera.com",
    "https://autotrader.com",
    "https://marketwatch.com",
    "https://jalan.net",
    "https://walgreens.com",
    "https://sky.com",
    "https://grammarly.com",
    "https://apollohospitals.com",
    "https://babycenter.com",
    "https://kakaku.com",
    "https://fresha.com",
    "https://digitalspy.com",
    "https://jooble.org",
    "https://lavanguardia.com",
    "https://lexiconlearning.com",
    "https://bhg.com",
    "https://vocabclass.com",
    "https://livemint.com",
    "https://readdork.com",
    "https://terra.com.br",
    "https://mit.edu",
    "https://byrdie.com",
    "https://eater.com",
    "https://metacritic.com",
    "https://ecured.cu",
    "https://elmundo.es",
    "https://aptoide.com",
    "https://mdpi.com",
    "https://yelp.co.uk",
    "https://idntimes.com",
    "https://womenshealthmag.com",
    "https://eatingwell.com",
    "https://mabumbe.com",
    "https://ibm.com",
    "https://standard.co.uk",
    "https://oup.com",
    "https://cargurus.com",
    "https://thebump.com",
    "https://amazon.com.mx",
    "https://abril.com.br",
    "https://dasoertliche.de",
    "https://vectorstock.com",
    "https://eonline.com",
    "https://apkpure.net",
    "https://unitconverters.net",
    "https://pixiv.net",
    "https://holidaycheck.de",
    "https://lemonde.fr",
    "https://cntraveler.com",
    "https://delish.com",
    "https://state.gov",
    "https://thepioneerwoman.com",
    "https://tribuna.com",
    "https://moviefone.com",
    "https://thetimes.com",
    "https://comicbook.com",
    "https://india.com",
    "https://mail.ru",
    "https://rocketreach.co",
    "https://zara.com",
    "https://abplive.com",
    "https://cancer.gov",
    "https://autozone.com",
    "https://nikkei.com",
    "https://hubpages.com",
    "https://allmusic.com",
    "https://digitaltrends.com",
    "https://moviepilot.de",
    "https://gettyimages.es",
    "https://playstation.com",
    "https://smule.com",
    "https://deadline.com",
    "https://studysmarter.co.uk",
    "https://ticketmaster.com",
    "https://bild.de",
    "https://hotpepper.jp",
    "https://olympics.com",
    "https://bleacherreport.com",
    "https://streetdirectory.com",
    "https://focus.de",
    "https://jagranjosh.com",
    "https://worldpopulationreview.com",
    "https://realsimple.com",
    "https://niche.com",
    "https://theknot.com",
    "https://pixnet.net",
    "https://nbcsports.com",
    "https://engoo.com",
    "https://cvs.com",
    "https://mynavi.jp",
    "https://squarespace.com",
    "https://yandex.kz",
    "https://rogerebert.com",
    "https://simplyrecipes.com",
    "https://kompass.com",
    "https://almanac.com",
    "https://eventbrite.com",
    "https://toasttab.com",
    "https://bonappetit.com",
    "https://pressbooks.pub",
    "https://meteoblue.com",
    "https://betterhealth.vic.gov.au",
    "https://dexerto.com",
    "https://ludwig.guru",
    "https://statista.com",
    "https://un.org",
    "https://fc2.com",
    "https://esquire.com",
    "https://11880.com",
    "https://justia.com",
    "https://fda.gov",
    "https://xe.com",
    "https://linguee.es",
    "https://verywellmind.com",
    "https://teacherspayteachers.com",
    "https://translate.com",
    "https://next.co.uk",
    "https://komoot.com",
    "https://miraheze.org",
    "https://kaiserpermanente.org",
    "https://fnac.com",
    "https://angi.com",
    "https://ardmediathek.de",
    "https://okdiario.com",
    "https://mercadolibre.com.ar",
    "https://cdiscount.com",
    "https://lerobert.com",
    "https://noaa.gov",
    "https://petmd.com",
    "https://clarin.com",
    "https://diy.com",
    "https://pearson.com",
    "https://biblestudytools.com",
    "https://wunderground.com",
    "https://alc.co.jp",
    "https://biblehub.com",
    "https://livejournal.com",
    "https://lifewire.com",
    "https://senscritique.com",
    "https://kroger.com",
    "https://lyst.com",
    "https://hinkhoj.com",
    "https://marketscreener.com",
    "https://blibli.com",
    "https://linternaute.fr",
    "https://food52.com",
    "https://airbnb.com",
    "https://123rf.com",
    "https://cnrtl.fr",
    "https://ndr.de",
    "https://iheart.com",
    "https://petitfute.com",
    "https://bible.com",
    "https://coursera.org",
    "https://golocal.de",
    "https://kohls.com",
    "https://euronews.com",
    "https://jdpower.com",
    "https://farfetch.com",
    "https://patient.info",
    "https://allen.in",
    "https://wattpad.com",
    "https://patch.com",
    "https://prtimes.jp",
    "https://popsugar.com",
    "https://easemytrip.com",
    "https://tureng.com",
    "https://spiegel.de",
    "https://retty.me",
    "https://mumsnet.com",
    "https://game8.co",
    "https://eksisozluk.com",
    "https://halodoc.com",
    "https://unam.mx",
    "https://tractorsupply.com",
    "https://usmagazine.com",
    "https://boomplay.com",
    "https://ok.ru",
    "https://slashfilm.com",
    "https://wikwik.org",
    "https://epicurious.com",
    "https://virgilio.it",
    "https://michelin.com",
    "https://dzen.ru",
    "https://rateyourmusic.com",
    "https://showmeword.com",
    "https://kinorium.com",
    "https://wa.gov",
    "https://xbox.com",
    "https://polygon.com",
    "https://jstor.org",
    "https://snappywords.com",
    "https://travelweekly.com",
    "https://techtarget.com",
    "https://myntra.com",
    "https://lonelyplanet.com",
    "https://tesco.com",
    "https://my-best.com",
    "https://prnewswire.com",
    "https://slashgear.com",
    "https://welt.de",
    "https://nine.com.au",
    "https://taste.com.au",
    "https://dictzone.com",
    "https://epicentrk.ua",
    "https://expedia.co.uk",
    "https://paginegialle.it",
    "https://elespanol.com",
    "https://rapidtables.com",
    "https://dcinside.com",
    "https://rd.com",
    "https://livescore.com",
    "https://zmenu.com",
    "https://osmosis.org",
    "https://songtexte.com",
    "https://boots.com",
    "https://sensacine.com",
    "https://treccani.it",
    "https://wikiquote.org",
    "https://tripadvisor.jp",
    "https://chosun.com",
    "https://ukr.net",
    "https://tripadvisor.com.sg",
    "https://psu.edu",
    "https://gizmodo.com",
    "https://tutorialspoint.com",
    "https://dev.to",
    "https://mapion.co.jp",
    "https://lastminute.com",
    "https://purdue.edu",
    "https://steemit.com",
    "https://educalingo.com",
    "https://thriftbooks.com",
    "https://w3schools.com",
    "https://instyle.com",
    "https://dict.cc",
    "https://seamless.com",
    "https://concepto.de",
    "https://twinkl.com",
    "https://flightaware.com",
    "https://bills.com.au",
    "https://bookmyshow.com",
    "https://youglish.com",
    "https://nba.com",
    "https://nintendo.com",
    "https://significadode.org",
    "https://elperiodico.com",
    "https://meinestadt.de",
    "https://allure.com",
    "https://globalnews.ca",
    "https://hellomagazine.com",
    "https://mp.gov.in",
    "https://singleplatform.com",
    "https://convertunits.com",
    "https://indiatoday.in",
    "https://brunch.co.kr",
    "https://wondershare.com",
    "https://wego.com",
    "https://tripadvisor.com.hk",
    "https://chewy.com",
    "https://menu-world.com",
    "https://scmp.com",
    "https://uml.edu.ni",
    "https://travelmath.com",
    "https://motortrend.com",
    "https://allegro.pl",
    "https://shaalaa.com",
    "https://ctvnews.ca",
    "https://espn.co.uk",
    "https://giphy.com",
    "https://20minutos.es",
    "https://refinery29.com",
    "https://theweathernetwork.com",
    "https://shiksha.com",
    "https://kotobank.jp",
    "https://aarp.org",
    "https://bustle.com",
    "https://wanderboat.ai",
    "https://morningstar.com",
    "https://calculatorsoup.com",
    "https://wisc.edu",
    "https://pantip.com",
    "https://glamour.com",
    "https://definicion.de",
    "https://kinopoisk.ru",
    "https://amazon.nl",
    "https://bloomingdales.com",
    "https://uefa.com",
    "https://hp.com",
    "https://theglobeandmail.com",
    "https://findlaw.com",
    "https://menards.com",
    "https://verywellfit.com",
    "https://news-medical.net",
    "https://res-menu.net",
    "https://weather.gov",
    "https://beebom.com",
    "https://tradeindia.com",
    "https://statmuse.com",
    "https://pw.live",
    "https://ft.com",
    "https://countryliving.com",
    "https://gosupps.com",
    "https://makeuseof.com",
    "https://ubiehealth.com",
    "https://mymovies.it",
    "https://crosswordsolver.com",
    "https://cinemablend.com",
    "https://trendyol.com",
    "https://hamariweb.com",
    "https://harpersbazaar.com",
    "https://thewrap.com",
    "https://pngwing.com",
    "https://adac.de",
    "https://libguides.com",
    "https://nhsinform.scot",
    "https://livedoor.com",
    "https://coursehero.com",
    "https://gettyimages.it",
    "https://news.com.au",
    "https://filmstarts.de",
    "https://weatherbug.com",
    "https://stern.de",
    "https://prokerala.com",
    "https://nfl.com",
    "https://osu.edu",
    "https://fernsehserien.de",
    "https://howtogeek.com",
    "https://cozycozy.com",
    "https://berkeley.edu",
    "https://seatgeek.com",
    "https://zendesk.com",
    "https://udn.com",
    "https://careers360.com",
    "https://commonsensemedia.org",
    "https://iherb.com",
    "https://eurogamer.net",
    "https://asahi.com",
    "https://noon.com",
    "https://metro.co.uk",
    "https://bilibili.tv",
    "https://dazn.com",
    "https://orbitz.com",
    "https://order.online",
    "https://footystats.org",
    "https://marksandspencer.com",
    "https://decider.com",
    "https://vinmec.com",
    "https://pcgamer.com",
    "https://bandcamp.com",
    "https://vulture.com",
    "https://calculateme.com",
    "https://msu.edu",
    "https://crunchyroll.com",
    "https://umn.edu",
    "https://gnavi.co.jp",
    "https://corner.inc",
    "https://fabriciano.mg.gov.br",
    "https://tradingeconomics.com",
    "https://gettyimages.de",
    "https://michaels.com",
    "https://reserving.com",
    "https://argos.co.uk",
    "https://cliffsnotes.com",
    "https://twitch.tv",
    "https://tempo.co",
    "https://cnnbrasil.com.br",
    "https://radiopaedia.org",
    "https://24timezones.com",
    "https://goibibo.com",
    "https://data.gouv.fr",
    "https://gq.com",
    "https://samsclub.com",
    "https://repubblica.it",
    "https://holidify.com",
    "https://livescores.biz",
    "https://revolut.com",
    "https://bigw.com.au",
    "https://smithsonianmag.com",
    "https://legacy.com",
    "https://linguee.fr",
    "https://bunnings.com.au",
    "https://aaa.com",
    "https://calculator.net",
    "https://firstcry.com",
    "https://gettyimages.co.uk",
    "https://moviemeter.com",
    "https://moviesanywhere.com",
    "https://trivago.com",
    "https://soccerway.com",
    "https://tripadvisor.at",
    "https://gaana.com",
    "https://travelandleisure.com",
    "https://ekiten.jp",
    "https://tripadvisor.co",
    "https://physio-pedia.com",
    "https://dillards.com",
    "https://fool.com",
    "https://univision.com",
    "https://kenhub.com",
    "https://gettyimages.in",
    "https://mydramalist.com",
    "https://vrbo.com",
    "https://freethesaurus.com",
    "https://wiki.gg",
    "https://churchofjesuschrist.org",
    "https://guestreservations.com",
    "https://mapfan.com",
    "https://fastercapital.com",
    "https://go.com",
    "https://mapsofworld.com",
    "https://forvo.com",
    "https://gsmarena.com",
    "https://lanacion.com.ar",
    "https://ufl.edu",
    "https://finedictionary.com",
    "https://ahdictionary.com",
    "https://songfacts.com",
    "https://abc.es",
    "https://familysearch.org",
    "https://canadiantire.ca",
    "https://thesprucepets.com",
    "https://jw.org",
    "https://brandclub.com",
    "https://sky.it",
    "https://ycombinator.com",
    "https://estadao.com.br",
    "https://ancestry.com",
    "https://columbia.edu",
    "https://sueddeutsche.de",
    "https://epa.gov",
    "https://kapanlagi.com",
    "https://yumpu.com",
    "https://calculat.io",
    "https://faz.net",
    "https://ucdavis.edu",
    "https://nicovideo.jp",
    "https://journaldesfemmes.fr",
    "https://search.ch",
    "https://filmibeat.com",
    "https://myanimelist.net",
    "https://skyscanner.com",
    "https://doccheck.com",
    "https://songmeanings.com",
    "https://irs.gov",
    "https://umich.edu",
    "https://punchfork.com",
    "https://nme.com",
    "https://biography.com",
    "https://fctables.com",
    "https://nyc.gov",
    "https://elcomercio.pe",
    "https://sirved.com",
    "https://tsn.ua",
    "https://vividseats.com",
    "https://onefootball.com",
    "https://rei.com",
    "https://eltiempo.com",
    "https://cybo.com",
    "https://lyrics.com",
    "https://tripadvisor.com.br",
    "https://autoevolution.com",
    "https://vietnam.vn",
    "https://franceinfo.fr",
    "https://olx.com.br",
    "https://brainly.co.id",
    "https://skyscanner.net",
    "http://facebook.com"
]

def login(email):
    payload = {
        "email": email,
        "password": PASSWORD,
    }

    response = requests.post(
        LOGIN_USER_API,
        json=payload,
        timeout=10,
    )

    if response.status_code != 200:
        print(f"Login failed for {email}")
        print(response.text)
        return None

    data = response.json()
    # Adjust this if your response format is different
    return data["access_token"]


# ======================================================================
# Main
# ======================================================================

# Uncomment once if users don't exist
create_users()

users = get_users()
urls = all_urls

if not users:
    raise Exception("No users found.")

if not urls:
    raise Exception("No URLs found.")

print(f"Loaded {len(users)} users.")
print(f"Loaded {len(urls)} URLs.")

success = 0

for i in range(TOTAL_URLS):
    email = random.choice(users)
    original_url = random.choice(urls)
    token = login(email)
    if token is None:
        continue
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    payload = {
        "original_url": original_url,
    }
    response = requests.post(
        CREATE_URL_API,
        headers=headers,
        json=payload,
        timeout=10,
    )

    if response.status_code == 200:
        success += 1
        print(f"[{success}/{TOTAL_URLS}] " f"{email} -> {original_url}")
    else:
        print(f"Failed ({response.status_code}) " f"for {email}")
        print(response.text)

print("=" * 70)
print(f"Successfully created {success} URLs.")
print("=" * 70)


TOTAL_CLICKS = 4000


def get_short_urls():
    db = next(get_db())
    records = db.query(URLModel).all()
    return [record.short_code for record in records]


short_urls = get_short_urls()

if not short_urls:
    raise Exception("No URLs found.")

success = 0

for i in range(TOTAL_CLICKS):

    short_code = random.choice(short_urls)

    response = requests.get(
        f"{DOMAIN}/{short_code}",
        allow_redirects=False,
        timeout=10,
    )

    if response.status_code in (200, 301, 302, 307, 308):
        success += 1
        print(f"[{success}/{TOTAL_CLICKS}] {short_code}")
    else:
        print(f"Failed ({response.status_code}) -> {short_code}")

print(f"\nGenerated {success} clicks.")
